# SPDX-License-Identifier: MIT OR GPL-3.0-or-later
from ..vrm1.human_bone import HumanBoneSpecification, HumanBoneSpecifications

mapping: dict[str, HumanBoneSpecification] = {
    "Bip001Pelvis": HumanBoneSpecifications.HIPS,
    "Bip001Spine": HumanBoneSpecifications.SPINE,
    "Bip001Spine2": HumanBoneSpecifications.CHEST,
    "Bip001Neck": HumanBoneSpecifications.NECK,
    "Bip001Head": HumanBoneSpecifications.HEAD,
    "Eye01": HumanBoneSpecifications.RIGHT_EYE,
    "Eye01": HumanBoneSpecifications.LEFT_EYE,
    "Bip001RClavicle": HumanBoneSpecifications.RIGHT_SHOULDER,
    "Bip001RUpperArm": HumanBoneSpecifications.RIGHT_UPPER_ARM,
    "Bip001RForearm": HumanBoneSpecifications.RIGHT_LOWER_ARM,
    "Bip001RHand": HumanBoneSpecifications.RIGHT_HAND,
    "Bip001LClavicle": HumanBoneSpecifications.LEFT_SHOULDER,
    "Bip001LUpperArm": HumanBoneSpecifications.LEFT_UPPER_ARM,
    "Bip001LForearm": HumanBoneSpecifications.LEFT_LOWER_ARM,
    "Bip001LHand": HumanBoneSpecifications.LEFT_HAND,
    "Bip001RThigh": HumanBoneSpecifications.RIGHT_UPPER_LEG,
    "Bip001RCalf": HumanBoneSpecifications.RIGHT_LOWER_LEG,
    "Bip001RFoot": HumanBoneSpecifications.RIGHT_FOOT,
    "Bip001RToe0": HumanBoneSpecifications.RIGHT_TOES,
    "Bip001LThigh": HumanBoneSpecifications.LEFT_UPPER_LEG,
    "Bip001LCalf": HumanBoneSpecifications.LEFT_LOWER_LEG,
    "Bip001LFoot": HumanBoneSpecifications.LEFT_FOOT,
    "Bip001LToe0": HumanBoneSpecifications.LEFT_TOES,
    "Bip001RFinger0": HumanBoneSpecifications.RIGHT_THUMB_METACARPAL,
    "Bip001RFinger01": HumanBoneSpecifications.RIGHT_THUMB_PROXIMAL,
    "Bip001RFinger02": HumanBoneSpecifications.RIGHT_THUMB_DISTAL,
    "Bip001LFinger0": HumanBoneSpecifications.LEFT_THUMB_METACARPAL,
    "Bip001LFinger01": HumanBoneSpecifications.LEFT_THUMB_PROXIMAL,
    "Bip001LFinger02": HumanBoneSpecifications.LEFT_THUMB_DISTAL,
    "Bip001RFinger1": HumanBoneSpecifications.RIGHT_INDEX_PROXIMAL,
    "Bip001RFinger11": HumanBoneSpecifications.RIGHT_INDEX_INTERMEDIATE,
    "Bip001RFinger12": HumanBoneSpecifications.RIGHT_INDEX_DISTAL,
    "Bip001LFinger1": HumanBoneSpecifications.LEFT_INDEX_PROXIMAL,
    "Bip001LFinger11": HumanBoneSpecifications.LEFT_INDEX_INTERMEDIATE,
    "Bip001LFinger12": HumanBoneSpecifications.LEFT_INDEX_DISTAL,
    "Bip001RFinger2": HumanBoneSpecifications.RIGHT_MIDDLE_PROXIMAL,
    "Bip001RFinger21": HumanBoneSpecifications.RIGHT_MIDDLE_INTERMEDIATE,
    "Bip001RFinger22": HumanBoneSpecifications.RIGHT_MIDDLE_DISTAL,
    "Bip001LFinger2": HumanBoneSpecifications.LEFT_MIDDLE_PROXIMAL,
    "Bip001LFinger21": HumanBoneSpecifications.LEFT_MIDDLE_INTERMEDIATE,
    "Bip001LFinger22": HumanBoneSpecifications.LEFT_MIDDLE_DISTAL,
    "Bip001RFinger3": HumanBoneSpecifications.RIGHT_RING_PROXIMAL,
    "Bip001RFinger31": HumanBoneSpecifications.RIGHT_RING_INTERMEDIATE,
    "Bip001RFinger32": HumanBoneSpecifications.RIGHT_RING_DISTAL,
    "Bip001LFinger3": HumanBoneSpecifications.LEFT_RING_PROXIMAL,
    "Bip001LFinger31": HumanBoneSpecifications.LEFT_RING_INTERMEDIATE,
    "Bip001LFinger32": HumanBoneSpecifications.LEFT_RING_DISTAL,
    "Bip001RFinger4": HumanBoneSpecifications.RIGHT_LITTLE_PROXIMAL,
    "Bip001RFinger41": HumanBoneSpecifications.RIGHT_LITTLE_INTERMEDIATE,
    "Bip001RFinger42": HumanBoneSpecifications.RIGHT_LITTLE_DISTAL,
    "Bip001LFinger4": HumanBoneSpecifications.LEFT_LITTLE_PROXIMAL,
    "Bip001LFinger41": HumanBoneSpecifications.LEFT_LITTLE_INTERMEDIATE,
    "Bip001LFinger42": HumanBoneSpecifications.LEFT_LITTLE_DISTAL
}



config_wuwa = ("wuwa(VRM1)", mapping)
